apiVersion: apps/v1
kind: Deployment
metadata:
  name: kweightly
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kweightly
  template:
    metadata:
      labels:
        app: kweightly
    spec:
      containers:
        - name: kweightly
          image: carstendev/kweightly:latest
          ports:
            - containerPort: 9002
            - containerPort: 9003