apiVersion: v1
kind: Service
metadata:
  name: weight-service
  labels:
    app: kweightly
spec:
  selector:
    app: kweightly
  type: LoadBalancer
  ports:
    - name: main
      port: 9002
      targetPort: 9002
    - name: health
      port: 9003
      targetPort: 9003