apiVersion: apps/v1
kind: Deployment
metadata:
  name: kweightly-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kweightly
  template:
    metadata:
      labels:
        app: kweightly
    spec:
      containers:
        - name: kweightly
          image: carstendev/kweightly:27a8c1d13be8e332a4829f916ee333acce6323f3
          ports:
            - containerPort: 9002
            - containerPort: 9003
          envFrom:
            - configMapRef:
                name: kweightly-env

---
apiVersion: v1
kind: Service
metadata:
  name: kweightly
  labels:
    app: kweightly
spec:
  selector:
    app: kweightly
  type: NodePort
  ports:
    - name: main
      port: 9002
      targetPort: 9002
      nodePort: 30080
    - name: health
      port: 9003
      targetPort: 9003
      nodePort: 30081
